### ISSUE TITLE
[Feature Request] Output colored text

### ISSUE THREAD

**Issue by lnxbil** [elk-language/go-prompt#20]
I wonder if it is possible to use the library to output colored text. Having coloring with the Lexer is simple and easy to archieve, yet if I just want to have some `fmt.Println` wrapper to use the defined color, it would be great. Is this already possible?

**Comment by lnxbil** [comment]
To partly answer my own question:

Yes it is currently possible with such a construction:

```go
writer := prompt.NewStandardOutputWriter()
writer.SetColor(prompt.Red, prompt.DefaultColor, false)
writer.WriteString("Test\n")
writer.SetColor(prompt.DefaultColor, prompt.DefaultColor, false)
writer.Flush()
```

Can this be done shorter?

**Comment by Verseth** [comment]
Honestly, these APIs were probably designed for internal use.

One of the most annoying architectural decisions of this library for me is that the original author decided to create his own text colouring logic instead of using a third party library.

That's why it's quite limited and incomplete.

I considered refactoring the code to get rid of the proprietary text colouring but I ultimately decided to leave it for now.

I'd recommend that you use another library for printing your own coloured text that doesn't need to go through the rendering pipeline of this library.

Something like https://github.com/fatih/color should do just fine.

**Comment by lnxbil** [comment]
Thank you, I've used fatih's library before yet thought, I can omit it this time around.
